package decoding;
import java.util.Scanner;

public class Main {
	private static String ENCRYPTED_TEXT_TASK_2 = "EFFPQLMEHEMVPCPYFLMVHQLUHYTCETHQEKLPVMMVHQLUWEOLFPQLIVDLWLULMVHQLUCYAUHUYDUEOSQYATFFVSMUVOVWEPLPQVSPCHLYGETDYUVPQOGUYOOYWYETHQEKLPVMYWLSASVWDEWCPLSPYGDYYFWLSSYGGVPCYAEULMYOGYUPEKTLBVPQCYAOECASLVWFLRYGMYVWMVFLWMLNESVSNVLREOVWEPVYWSPEPVSPVMETPLSPSYUBQEPLILUOLPQYFCYAGLLTBVTTSQYBPQLKLSPULSATPPUCPYPQVWNYGBQEPBVTTQEHHLWVGPQLNLCMYWPEVWSSEOLMQEUEMPLUSEPFVGGLULWPHYSVPVYWSBVTTCYAUHUYDUEOSPVTTKLQEILMYUULMPTC";
	private static String ENCRYPTED_TEXT_TASK_3 = "EDVRLESZMLARCTGBICANLEJYRYCGRDGDTODWELHFEBWRMCUGTHWPWTZCSNWSWEVGRTZCGIHFIRLCBTKFIRWFESLUINLWWIPGRDWNINVCRTJYRDGKPYUFSSWLQOFMELHFEBWRMCKSFSLGXULGSNHYXTWPRSXMVESALLWRXEJDVOECRGDGWHSJTHSZITARMSUJIAJRLALWSUUYRNGKSRWPILQMRTZCWAECWIENPEJMYTALIOXEYEKQMNYRLECCCBQCBHSSWTATISWYVCZULIUFCOMNVOTYFLQSWEVRSDWAMPZCVTZGWPSPEGJYTHOGPLLFIIFBIXGDGOALGIVCRCWQXIDJAOJIESSQYGYCWTAMRYGSGAFRVYLMHINGHELFIMWQWAYCMNHYVTKZCTZCRUEZIRGDGHSPECLCVSALEKWWENVYTPDWJRWOYEFACAFYPYKGWTGCECZMJTZCQCSLCOMDMNVYAAQRSUKCLIYFIRGPHEJDVEISINUWWTSRMSLGGSOGXHLFMSLWTEGDGIHFIRLFINWVXPSPEGJYTHUMRTSGRSKMQEHPITLWMNLCVEKRMNYGRFGPQALGSNSZSULQSMWYHDARMOFYPRWUERV";
	private static String ENCRYPTED_TEXT_TASK_4 = "UOWZWZTIDHMORKKLREROAESKWOELRVAPAIDNRAGKVFTYLZDOTXTENKFVNTRLUSTYHKESTUPPTZRUOFJSLCIWLJLOTDAIOERMSODHWRIQHJARVIBLLPKPDDVQVNTYHAERILAORPRMUNZYLRSZWFASNHSLAJSVRTIDFALFIDHAKHEACKOFTOCRVKFFUAHEWLYSTFQLWHFGLCRPSASTYHSASKSPECVDUDFZQKSTYHWRIQHJANKDREIKDSLAEGPSTYHUFRVHAODFZOATVYLRHVZPSHVVAODFZPTHZWAHIJOHSTVQJRYGWLDTVAAISROTOSKWOEHRUKESKBVUCRQNETNLAHSZPWLEGRSYACSOABVWPCCZSOERJLAUTZOPZEJVVMEKHJHNZTBESKRKRIMHAHETUFPTRQHLYKLJAWRBMRODWOERZJOTDZULCTZRUMIJVWELCHKWOIGZMAEXHLLPFOANXHKCHRUHCTVUZBEWRYEEEFYYPKLVNMVDUINXOLSSTRTBIEDAIOEVVFLVWAERJLUCLLGLDBLWAHEGUVGRRPAODVFPPHVUAHIJWLXTRXAOMRWPCACOFWIKKVUTYXTANYHSPWZOSRETHPVEKZVMOIHWOIEWZINJWLADFIVNEPRBMAPZHNTKRZEAIFOFOIDDAYKRBSEBQVWNGOHINKHETAKWHCKRVFOUTDUGUVVZSODHDORUVVREMHUPHIDZESWUVMTYHSASKSHRAXUHPHGUVVIULUGTYHWROXUHMWZWOPOJVPBLVSSAIEWLXTGKYASVVKOEJQVTMRNLITERAAUKRTATZF";
	public static void main(String[] args) {
		
		Decoder decoder = new Decoder(ENCRYPTED_TEXT_TASK_2);
		//decoder.test();
		Scanner scanner = new Scanner(System.in);
		while(true){
			System.out.println("Input");
			String input = scanner.nextLine();
			switch(input){
			case "p": 
				decoder.printEncryptedTextWithDecryptedChars();
				break;
			case "p1":
				decoder.printFirstOrder();
				break;
			case "p2":
				decoder.printSecondOrder();
				break;
			case "p3":
				decoder.printThirdOrder();
				break;
			case "pd":
				decoder.printDecryptedData();
				break;
			case "w":
				String replacedChars = scanner.nextLine();
				decoder.addDecodeChar(""+replacedChars.charAt(0), ""+replacedChars.charAt(1));
				decoder.printEncryptedTextWithDecryptedChars();
				break;
			case "-w":
				String delDecodetChar = scanner.nextLine();
				decoder.removeDecodeChar(delDecodetChar);
				decoder.printEncryptedTextWithDecryptedChars();
				break;
			}
			
		}
		
	}

}
